### ISSUE TITLE
Add 'What schools are participating?'

### ISSUE THREAD

**Issue by fmitchell** [betterweekdays/mepe#19]
Add 'What schools are participating?' after 'What dates...'

"Students who attend these MEPE Fellowship Partner schools should apply: Albany State University, Benedict College, Bluefield State College, Claflin University, Clark Atlanta University, Dillard University,
Florida A&M University, Fayetteville State University, Fisk University, Huston Tillotson University, Jackson State University, Langston University, Morehouse College, Morgan State University, North Carolina A&T University, North Carolina Central University, Paul Quinn College, Prairie View A&M University, Spelman College, Stillman College, Tennessee State University, the University of Maryland Eastern Shore, Winston Salem State University, and Xavier University of Louisiana.

**Comment by AnnZhouCcc** [comment]
<img width="1440" alt="screen shot 2018-07-12 at 9 51 38 am" src="https://user-images.githubusercontent.com/35540935/42642059-9ab47dee-85bb-11e8-8850-0571e21bfa48.png">
<img width="1440" alt="screen shot 2018-07-12 at 9 43 13 am" src="https://user-images.githubusercontent.com/35540935/42642063-9c11fbb2-85bb-11e8-8326-d5d0974d4d5b.png">
I chose the former, but can switch

**Comment by AnnZhouCcc** [comment]
<img width="1321" alt="screen shot 2018-07-13 at 8 30 48 am" src="https://user-images.githubusercontent.com/35540935/42694844-450a29e8-8679-11e8-88ff-1c804d91dd07.png">
<img width="1322" alt="screen shot 2018-07-13 at 8 42 04 am" src="https://user-images.githubusercontent.com/35540935/42694847-4700ccf2-8679-11e8-82b0-146849c4622b.png">
4 columns v.s. 3 columns(chosen)
