### ISSUE TITLE
Content edit for Overview

### ISSUE THREAD

**Issue by AnnZhouCcc** [betterweekdays/mepe#5]
1. shorten history of Mary Ellen Pleasant
2. restructure overview of internship to deliver clearer message

**Comment by fmitchell** [comment]
The overview should be about the internship, not the history of MEP. 

> The Mary Ellen Pleasant Entrepreneurship (MEPE) Fellowship is a 10-week virtual internship during Spring 2019. Accepted fellows will be paid up to $2500 and build a mini-startup on campus.

**Comment by AnnZhouCcc** [comment]
This is the structure I have for now for the overview section.

1. History of MEP
2. Overview of internship
- What is the internship about?
- When and where is the internship happening?
- Why is the Soft Skills and Values Assessment so helpful?
- What can I get out of the 10-week experience?
- Who can apply to be a MEPE fellow?
3. Participating schools

What do you think of this structure?

**Comment by fmitchell** [comment]
This is good. I'd move the history to it's own section see #7 . The questions and answers are good. Perhaps we have a FAQ section. We do not need to include the schools
