### ISSUE TITLE
Copy updates

### ISSUE THREAD

**Issue by fmitchell** [betterweekdays/mepe#9]
- https://www.evernote.com/l/AOze00JcT5RN14gDBA_SsWi0jKlB_aCQHDk
- https://www.evernote.com/l/AOxmf1fwCTpKOblBtbJHYBJ3nbbAQTQDC6A
- https://www.evernote.com/l/AOzW6GsFOP1AJbQU7taxv7LvmzuyDa4K-dg
- https://www.evernote.com/l/AOyDrfMqpAZIbrINhrTaTiEA4j7jLiSw3gI
- https://www.evernote.com/l/AOwADq4vJ8xDqJ3yEpL8JFqVxO-pwcFCSTs
- https://www.evernote.com/l/AOyUx2NfZjlO5qd-7qBXsRcp_LjVizDTwGo
- https://www.evernote.com/l/AOyivDMPZ4tEQYVuuntCQq9Em8p-UDOZYEQ
- https://www.evernote.com/l/AOz2ZqJTWzNMKIipIE4hn0JPF2qC_-IOPas

**Comment by AnnZhouCcc** [comment]
<img width="1440" alt="screen shot 2018-06-20 at 9 09 53 am" src="https://user-images.githubusercontent.com/35540935/41664218-d0b540c0-746a-11e8-8fc5-b9468deaa6fa.png">
<img width="1440" alt="screen shot 2018-06-20 at 9 10 13 am" src="https://user-images.githubusercontent.com/35540935/41664221-d33bb07c-746a-11e8-8de8-8735a0ba2b55.png">
2 possible fonts here; i chose the latter, but can switch conveniently if needed
